"""Fire-and-forget audio cues for record / stop / done transitions.

Defaults ship as 1-second WAV files in `voxtype/resources/sounds/`
(generated by `scripts/gen_sounds.py`). Playback uses Windows'
built-in `winsound.PlaySound` because it's the OS-native API and
"just works" without needing an open output stream — sounddevice
was unreliable here when no PortAudio output stream was already
initialised. Non-WAV custom paths fall back to sounddevice +
soundfile.

Failures are logged and swallowed — a broken audio device must not
break dictation.
"""
from __future__ import annotations

import logging
import threading
from pathlib import Path
from typing import Literal

log = logging.getLogger("voxtype.sounds")

Cue = Literal["start", "stop", "done"]

_BUNDLED_DIR = Path(__file__).resolve().parent / "resources" / "sounds"


def _bundled_path(cue: str) -> Path:
    return _BUNDLED_DIR / f"{cue}.wav"


def _play_wav_winsound(path: Path) -> bool:
    """Returns True on success. Async — call returns immediately."""
    try:
        import winsound
        # SND_ASYNC: don't block. SND_FILENAME: path is a filename, not an
        # alias. SND_NODEFAULT: silent on missing file rather than playing
        # the Windows default beep.
        flags = (winsound.SND_FILENAME
                 | winsound.SND_ASYNC
                 | winsound.SND_NODEFAULT)
        winsound.PlaySound(str(path), flags)
        return True
    except Exception as exc:
        log.warning("winsound failed for %s: %s", path, exc)
        return False


def _play_via_sounddevice(path: Path) -> None:
    """Fallback for non-WAV custom paths (mp3/ogg/flac via libsndfile)."""
    try:
        import sounddevice as sd
        import soundfile as sf
        data, sr = sf.read(str(path), dtype="float32", always_2d=False)
        sd.play(data, sr, blocking=True)
    except Exception as exc:
        log.warning("sounddevice playback failed for %s: %s", path, exc)


def play(cue: Cue, custom_path: str = "") -> None:
    """Play a built-in cue or a user-provided audio file. Returns
    immediately — playback runs on a daemon thread."""
    def _do() -> None:
        # Resolve which file to play.
        target: Path | None = None
        if custom_path:
            p = Path(custom_path)
            if p.exists() and p.is_file():
                target = p
            else:
                log.warning("sound file not found, using default: %s", custom_path)
        if target is None:
            target = _bundled_path(cue)
            if not target.exists():
                log.warning("bundled sound missing: %s — "
                             "run `python scripts/gen_sounds.py`", target)
                return

        # Prefer winsound for .wav (Windows-native, super reliable).
        if target.suffix.lower() == ".wav":
            if _play_wav_winsound(target):
                return
        # Fallback path for non-WAV (or if winsound failed somehow).
        _play_via_sounddevice(target)

    threading.Thread(target=_do, daemon=True, name=f"voxtype-cue-{cue}").start()
