"""Settings + UI state types. Single source of truth.

STT and TTS both run in-process via PyTorch. An embedded HTTP server
(single port, default 6600) exposes them to external clients via
OpenAI-compatible endpoints — see voxtype/server.py.

Architecture: one generic STT backend and one generic TTS backend
auto-dispatch by HuggingFace `config.json` model_type / pipeline_tag
to the right handler (Whisper, Wav2Vec2, MMS, Seamless, Moonshine,
Kokoro, VITS, SpeechT5, Bark, Parler, …). Per-family knobs live in
the free-form `stt_opts` / `tts_opts` dicts so the UI can render
them dynamically without AppSettings ever needing to know about
family-specific fields.
"""
from __future__ import annotations

from dataclasses import dataclass, field, asdict
from typing import Any, Literal

PillState = Literal["idle", "recording", "processing", "enhancing", "typing", "error"]
HotkeyMode = Literal["hold", "toggle"]
# torch device preference. Used by both STT and TTS engines.
TorchDevice = Literal["cpu", "cuda"]
# Inference precision. `auto` = fp16 on CUDA, fp32 on CPU. `bf16` needs
# Ampere+ (RTX 30xx / A100+) — same speed as fp16, wider numeric range.
TorchDtype = Literal["auto", "fp32", "fp16", "bf16"]


@dataclass
class HotkeyCombo:
    """One or two keys that must be held together to activate the hotkey.

    Keys use pynput-style string names (e.g. "ctrl", "cmd", "f9") so we
    don't carry the Windows/uiohook numeric keycode over. `label` is
    human-readable."""
    key1: str = "ctrl"
    key2: str | None = "cmd"
    label: str = "Ctrl + Win"


@dataclass
class AppSettings:
    # ── Recording behavior ───────────────────────────────────────────
    hotkey_mode: HotkeyMode = "hold"
    hotkey: HotkeyCombo = field(default_factory=HotkeyCombo)
    auto_stop_on_silence: bool = True
    silence_duration_sec: float = 1.5
    vad_enabled: bool = True
    append_mode: bool = False

    # ── Voice activation ("start words") ─────────────────────────────
    # When enabled, an always-on listener segments the mic into short
    # utterances, transcribes each via the existing STT engine, and
    # begins a normal dictation capture when an utterance matches one of
    # the comma-separated `voice_start_words`. Off by default — the mic +
    # STT stay active while listening. Voice-triggered captures always
    # auto-stop on silence (there is no hotkey release to end them).
    voice_activation_enabled: bool = False
    voice_start_words: str = "computer"   # comma-separated trigger phrases
    voice_match_contains: bool = False    # False = prefix match, True = substring
    voice_max_phrase_sec: float = 2.5     # ignore longer utterances when scanning

    # ── Audio cues (start record / stop record / done) ───────────────
    # Empty path → built-in tone generated by voxtype.sounds. Otherwise
    # any sounddevice/soundfile-readable file (wav/flac/ogg/mp3 via libsndfile).
    sounds_enabled: bool = True
    sound_duration_sec: float = 0.5
    sound_start_enabled: bool = True
    sound_stop_enabled: bool = True
    sound_done_enabled: bool = True
    sound_start: str = ""
    sound_stop: str = ""
    sound_done: str = ""

    # ── Pill UI position (-1 = unset → center-bottom) ────────────────
    pill_x: int = -1
    pill_y: int = -1
    pill_hidden: bool = False
    # When True the pill is hidden while idle and only appears during
    # active states (recording / processing / enhancing / typing / error).
    pill_active_only: bool = False

    # ── OLED burn-in guard ───────────────────────────────────────────
    # Periodically flash a fullscreen black frame to give OLED pixels a
    # brief rest. Off by default. `oled_flashes_per_sec` is the only knob
    # the user sets — the per-flash duration is derived from the display
    # refresh rate (one frame), so higher-Hz panels flash less perceptibly.
    # See voxtype/oled_guard.py.
    oled_guard_enabled: bool = False
    oled_flashes_per_sec: int = 2
    # How dark the flash is: 1.0 = full black (max pixel rest, most
    # noticeable), lower = a translucent dim (gentler, less protection).
    oled_flash_opacity: float = 1.0

    # ── Embedded HTTP server ─────────────────────────────────────────
    server_enabled: bool = True
    server_port: int = 6600

    # ── Engine worker (out-of-process torch) ─────────────────────────
    # Seconds the worker stays alive with BOTH models unloaded before it
    # exits to release the CUDA context (~300-600 MB). The next request
    # respawns it. 0 = never exit (weights still unload per
    # stt/tts_idle_unload_sec, but the context lingers).
    engine_idle_exit_sec: int = 60

    # ── STT (one generic backend, family auto-detected) ─────────────
    # `stt_model_path` accepts any HF repo ID (auto-downloaded) or a
    # local path — Whisper, Wav2Vec2, HuBERT, MMS, Seamless,
    # Moonshine, SpeechT5, Voxtral, Granite-Speech, … The generic
    # backend sniffs the model's config.json and picks the right
    # loader.
    stt_enabled: bool = True
    stt_auto_start: bool = True
    stt_idle_unload_sec: int = 300
    stt_model_path: str = "openai/whisper-large-v3"
    stt_device: TorchDevice = "cpu"
    stt_language: str = "en"
    stt_dtype: TorchDtype = "auto"
    stt_warmup: bool = True
    stt_torch_compile: bool = False
    # Attention backend. `auto` lets transformers pick (sdpa on modern
    # versions); `flash_attention_2` requires fp16/bf16 + Ampere+; `eager`
    # is the safe fallback for exotic models.
    stt_attn_impl: str = "auto"
    # Long-form chunking for the embedded HTTP server. 0 = off (single-
    # utterance dictation never needs this).
    stt_chunk_length_s: int = 0
    stt_stride_length_s: int = 0
    # Family-specific per-call options. Populated by the UI from the
    # backend's runtime_options() spec list. Whisper writes `task`,
    # `num_beams`, `temperature`, `repetition_penalty`, `initial_prompt`;
    # Bark writes `semantic_temperature` / `coarse_temperature` / `min_eos_p`;
    # Parler writes `style`, `temperature`, `max_new_tokens`;
    # Voxtral / Granite / Phi-4 / Qwen-Audio write `prompt`;
    # SpeechT5 writes `speaker_embedding`; XTTS writes the full
    # temperature/top_p/top_k/repetition_penalty/length_penalty block.
    stt_opts: dict[str, Any] = field(default_factory=dict)

    # ── TTS (one generic backend, family auto-detected) ─────────────
    tts_enabled: bool = False
    tts_auto_start: bool = False
    tts_idle_unload_sec: int = 600
    tts_model_path: str = "hexgrad/Kokoro-82M"
    tts_device: TorchDevice = "cpu"
    tts_voice: str = "af_heart"
    tts_speed: float = 1.0
    tts_warmup: bool = True
    tts_torch_compile: bool = False
    tts_stream: bool = False
    # Mirror of stt_attn_impl for TTS handlers.
    tts_attn_impl: str = "auto"
    # Universal RNG seed. -1 = random. Honoured by VITS / Bark / Parler /
    # Orpheus / Higgs / etc. — anything sampling-based.
    tts_seed: int = -1
    tts_opts: dict[str, Any] = field(default_factory=dict)

    # ── LLM enhancement (via telecode proxy) ─────────────────────────
    enhance_enabled: bool = True
    screen_context: bool = True
    proxy_url: str = "http://127.0.0.1:1235"
    proxy_model: str = "qwen3.5-35b"

    # ── History ──────────────────────────────────────────────────────
    save_history: bool = True

    # ── Serialization helpers ────────────────────────────────────────

    def to_json(self) -> dict:
        return asdict(self)

    @classmethod
    def from_json(cls, d: dict) -> "AppSettings":
        hk = d.get("hotkey") or {}
        settings = cls(
            hotkey=HotkeyCombo(
                key1=hk.get("key1", "ctrl"),
                key2=hk.get("key2"),
                label=hk.get("label", "Ctrl + Win"),
            ),
        )
        for key, value in d.items():
            if key == "hotkey":
                continue
            if hasattr(settings, key):
                setattr(settings, key, value)
        return settings


def server_url(s: AppSettings) -> str:
    """Base URL for the embedded STT/TTS server."""
    return f"http://127.0.0.1:{s.server_port}"
